# Generated by Django 3.2.8 on 2021-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomfeature', '0002_alter_movie_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
