# Generated by Django 3.2.8 on 2021-11-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomfeature', '0003_alter_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
