# Generated by Django 3.2.8 on 2021-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('date_released', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
