# Generated by Django 3.2.8 on 2021-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_released',
            new_name='movie_date_released',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='movie_genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(default=''),
        ),
    ]
