# Generated by Django 3.2.8 on 2021-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20211029_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_date_released',
            field=models.DateTimeField(),
        ),
    ]
