# Generated by Django 3.2.8 on 2021-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_movie_movie_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_swiped',
            field=models.BooleanField(default=False),
        ),
    ]
